server:
  port: 8081
spring:
  application:
    name: GameServer
  datasource:
    url: jdbc:mysql://localhost:3306/gameserver
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      database: 0