server:
  port: 8083
grpc:
  server:
    port: 8082
spring:
  application:
    name: GameServer
  datasource:
    url: jdbc:mysql://localhost:3306/gameserver
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      database: 0
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.protobuf.KafkaProtobufSerializer
      properties:
        spring.json.add.type.headers: false
    consumer:
      group-id: player-register-group
      enable-auto-commit: false
      max-poll-records: 2000
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.protobuf.KafkaProtobufDeserializer
      properties:
        spring.json.trusted.packages: "*"    # 允许反序列化所有包
    properties:
      schema:
        registry:
          url: http://localhost:8081
    listener:
      type: batch
      ack-mode: MANUAL_IMMEDIATE  # 启用手动提交
      concurrency: 5
snowflake:
  worker-id: 1
  datacenter-id: 1