// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.4
// source: messages.proto

package main

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OrderType int32

const (
	OrderType_BUY  OrderType = 0
	OrderType_SELL OrderType = 1
)

// Enum value maps for OrderType.
var (
	OrderType_name = map[int32]string{
		0: "BUY",
		1: "SELL",
	}
	OrderType_value = map[string]int32{
		"BUY":  0,
		"SELL": 1,
	}
)

func (x OrderType) Enum() *OrderType {
	p := new(OrderType)
	*p = x
	return p
}

func (x OrderType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrderType) Descriptor() protoreflect.EnumDescriptor {
	return file_messages_proto_enumTypes[0].Descriptor()
}

func (OrderType) Type() protoreflect.EnumType {
	return &file_messages_proto_enumTypes[0]
}

func (x OrderType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrderType.Descriptor instead.
func (OrderType) EnumDescriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{0}
}

type OrderStatus int32

const (
	OrderStatus_PENDING        OrderStatus = 0
	OrderStatus_PARTIAL_FILLED OrderStatus = 1
	OrderStatus_FILLED         OrderStatus = 2
	OrderStatus_CANCELLED      OrderStatus = 3
)

// Enum value maps for OrderStatus.
var (
	OrderStatus_name = map[int32]string{
		0: "PENDING",
		1: "PARTIAL_FILLED",
		2: "FILLED",
		3: "CANCELLED",
	}
	OrderStatus_value = map[string]int32{
		"PENDING":        0,
		"PARTIAL_FILLED": 1,
		"FILLED":         2,
		"CANCELLED":      3,
	}
)

func (x OrderStatus) Enum() *OrderStatus {
	p := new(OrderStatus)
	*p = x
	return p
}

func (x OrderStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrderStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_messages_proto_enumTypes[1].Descriptor()
}

func (OrderStatus) Type() protoreflect.EnumType {
	return &file_messages_proto_enumTypes[1]
}

func (x OrderStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrderStatus.Descriptor instead.
func (OrderStatus) EnumDescriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{1}
}

type RegisterReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterReq) Reset() {
	*x = RegisterReq{}
	mi := &file_messages_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterReq) ProtoMessage() {}

func (x *RegisterReq) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterReq.ProtoReflect.Descriptor instead.
func (*RegisterReq) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RegisterReq) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type RegisterRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        int32                  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Uid           *int64                 `protobuf:"varint,2,opt,name=uid,proto3,oneof" json:"uid,omitempty"`
	Message       *string                `protobuf:"bytes,3,opt,name=message,proto3,oneof" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRes) Reset() {
	*x = RegisterRes{}
	mi := &file_messages_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRes) ProtoMessage() {}

func (x *RegisterRes) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRes.ProtoReflect.Descriptor instead.
func (*RegisterRes) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterRes) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *RegisterRes) GetUid() int64 {
	if x != nil && x.Uid != nil {
		return *x.Uid
	}
	return 0
}

func (x *RegisterRes) GetMessage() string {
	if x != nil && x.Message != nil {
		return *x.Message
	}
	return ""
}

type GetPlayerByUidReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           int64                  `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPlayerByUidReq) Reset() {
	*x = GetPlayerByUidReq{}
	mi := &file_messages_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPlayerByUidReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlayerByUidReq) ProtoMessage() {}

func (x *GetPlayerByUidReq) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlayerByUidReq.ProtoReflect.Descriptor instead.
func (*GetPlayerByUidReq) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{2}
}

func (x *GetPlayerByUidReq) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

type GetPlayerByUidRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           int64                  `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPlayerByUidRes) Reset() {
	*x = GetPlayerByUidRes{}
	mi := &file_messages_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPlayerByUidRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlayerByUidRes) ProtoMessage() {}

func (x *GetPlayerByUidRes) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlayerByUidRes.ProtoReflect.Descriptor instead.
func (*GetPlayerByUidRes) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{3}
}

func (x *GetPlayerByUidRes) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *GetPlayerByUidRes) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetPlayerByUidRes) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type PlayerGetItemReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           int64                  `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	ItemId        int32                  `protobuf:"varint,2,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	ItemNum       int32                  `protobuf:"varint,3,opt,name=item_num,json=itemNum,proto3" json:"item_num,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerGetItemReq) Reset() {
	*x = PlayerGetItemReq{}
	mi := &file_messages_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerGetItemReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerGetItemReq) ProtoMessage() {}

func (x *PlayerGetItemReq) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerGetItemReq.ProtoReflect.Descriptor instead.
func (*PlayerGetItemReq) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{4}
}

func (x *PlayerGetItemReq) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *PlayerGetItemReq) GetItemId() int32 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

func (x *PlayerGetItemReq) GetItemNum() int32 {
	if x != nil {
		return x.ItemNum
	}
	return 0
}

type PlayerGetItemRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemId        int32                  `protobuf:"varint,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	ItemNum       int32                  `protobuf:"varint,2,opt,name=item_num,json=itemNum,proto3" json:"item_num,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerGetItemRes) Reset() {
	*x = PlayerGetItemRes{}
	mi := &file_messages_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerGetItemRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerGetItemRes) ProtoMessage() {}

func (x *PlayerGetItemRes) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerGetItemRes.ProtoReflect.Descriptor instead.
func (*PlayerGetItemRes) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{5}
}

func (x *PlayerGetItemRes) GetItemId() int32 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

func (x *PlayerGetItemRes) GetItemNum() int32 {
	if x != nil {
		return x.ItemNum
	}
	return 0
}

type GetItemListReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           int64                  `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetItemListReq) Reset() {
	*x = GetItemListReq{}
	mi := &file_messages_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetItemListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetItemListReq) ProtoMessage() {}

func (x *GetItemListReq) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetItemListReq.ProtoReflect.Descriptor instead.
func (*GetItemListReq) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{6}
}

func (x *GetItemListReq) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

type GetItemListRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Info          []*PlayerItem          `protobuf:"bytes,1,rep,name=info,proto3" json:"info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetItemListRes) Reset() {
	*x = GetItemListRes{}
	mi := &file_messages_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetItemListRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetItemListRes) ProtoMessage() {}

func (x *GetItemListRes) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetItemListRes.ProtoReflect.Descriptor instead.
func (*GetItemListRes) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{7}
}

func (x *GetItemListRes) GetInfo() []*PlayerItem {
	if x != nil {
		return x.Info
	}
	return nil
}

type PlayerItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           int64                  `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	ItemId        int32                  `protobuf:"varint,2,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	ItemNum       int32                  `protobuf:"varint,3,opt,name=item_num,json=itemNum,proto3" json:"item_num,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerItem) Reset() {
	*x = PlayerItem{}
	mi := &file_messages_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerItem) ProtoMessage() {}

func (x *PlayerItem) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerItem.ProtoReflect.Descriptor instead.
func (*PlayerItem) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{8}
}

func (x *PlayerItem) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *PlayerItem) GetItemId() int32 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

func (x *PlayerItem) GetItemNum() int32 {
	if x != nil {
		return x.ItemNum
	}
	return 0
}

type RegisterEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           int64                  `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterEvent) Reset() {
	*x = RegisterEvent{}
	mi := &file_messages_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterEvent) ProtoMessage() {}

func (x *RegisterEvent) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterEvent.ProtoReflect.Descriptor instead.
func (*RegisterEvent) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{9}
}

func (x *RegisterEvent) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *RegisterEvent) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RegisterEvent) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type PlaceOrderReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemId        string                 `protobuf:"bytes,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	Type          OrderType              `protobuf:"varint,2,opt,name=type,proto3,enum=OrderType" json:"type,omitempty"`
	Quantity      int32                  `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Price         int32                  `protobuf:"varint,4,opt,name=price,proto3" json:"price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlaceOrderReq) Reset() {
	*x = PlaceOrderReq{}
	mi := &file_messages_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlaceOrderReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlaceOrderReq) ProtoMessage() {}

func (x *PlaceOrderReq) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlaceOrderReq.ProtoReflect.Descriptor instead.
func (*PlaceOrderReq) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{10}
}

func (x *PlaceOrderReq) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

func (x *PlaceOrderReq) GetType() OrderType {
	if x != nil {
		return x.Type
	}
	return OrderType_BUY
}

func (x *PlaceOrderReq) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *PlaceOrderReq) GetPrice() int32 {
	if x != nil {
		return x.Price
	}
	return 0
}

type PlaceOrderRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       int64                  `protobuf:"varint,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Status        OrderStatus            `protobuf:"varint,2,opt,name=status,proto3,enum=OrderStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlaceOrderRes) Reset() {
	*x = PlaceOrderRes{}
	mi := &file_messages_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlaceOrderRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlaceOrderRes) ProtoMessage() {}

func (x *PlaceOrderRes) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlaceOrderRes.ProtoReflect.Descriptor instead.
func (*PlaceOrderRes) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{11}
}

func (x *PlaceOrderRes) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *PlaceOrderRes) GetStatus() OrderStatus {
	if x != nil {
		return x.Status
	}
	return OrderStatus_PENDING
}

type GetMarketDepthReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemId        string                 `protobuf:"bytes,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMarketDepthReq) Reset() {
	*x = GetMarketDepthReq{}
	mi := &file_messages_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMarketDepthReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMarketDepthReq) ProtoMessage() {}

func (x *GetMarketDepthReq) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMarketDepthReq.ProtoReflect.Descriptor instead.
func (*GetMarketDepthReq) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{12}
}

func (x *GetMarketDepthReq) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

func (x *GetMarketDepthReq) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetMarketDepthRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bids          []*OrderEntry          `protobuf:"bytes,1,rep,name=bids,proto3" json:"bids,omitempty"`
	Asks          []*OrderEntry          `protobuf:"bytes,2,rep,name=asks,proto3" json:"asks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMarketDepthRes) Reset() {
	*x = GetMarketDepthRes{}
	mi := &file_messages_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMarketDepthRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMarketDepthRes) ProtoMessage() {}

func (x *GetMarketDepthRes) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMarketDepthRes.ProtoReflect.Descriptor instead.
func (*GetMarketDepthRes) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{13}
}

func (x *GetMarketDepthRes) GetBids() []*OrderEntry {
	if x != nil {
		return x.Bids
	}
	return nil
}

func (x *GetMarketDepthRes) GetAsks() []*OrderEntry {
	if x != nil {
		return x.Asks
	}
	return nil
}

type OrderEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Price         int32                  `protobuf:"varint,1,opt,name=price,proto3" json:"price,omitempty"`
	Quantity      int32                  `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderEntry) Reset() {
	*x = OrderEntry{}
	mi := &file_messages_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderEntry) ProtoMessage() {}

func (x *OrderEntry) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderEntry.ProtoReflect.Descriptor instead.
func (*OrderEntry) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{14}
}

func (x *OrderEntry) GetPrice() int32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *OrderEntry) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

var File_messages_proto protoreflect.FileDescriptor

const file_messages_proto_rawDesc = "" +
	"\n" +
	"\x0emessages.proto\"8\n" +
	"\fregister_req\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\"p\n" +
	"\fregister_res\x12\x16\n" +
	"\x06status\x18\x01 \x01(\x05R\x06status\x12\x15\n" +
	"\x03uid\x18\x02 \x01(\x03H\x00R\x03uid\x88\x01\x01\x12\x1d\n" +
	"\amessage\x18\x03 \x01(\tH\x01R\amessage\x88\x01\x01B\x06\n" +
	"\x04_uidB\n" +
	"\n" +
	"\b_message\"&\n" +
	"\x12getPlayerByUid_req\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\x03R\x03uid\"P\n" +
	"\x12getPlayerByUid_res\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\x03R\x03uid\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\"Y\n" +
	"\x11playerGetItem_req\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\x03R\x03uid\x12\x17\n" +
	"\aitem_id\x18\x02 \x01(\x05R\x06itemId\x12\x19\n" +
	"\bitem_num\x18\x03 \x01(\x05R\aitemNum\"G\n" +
	"\x11playerGetItem_res\x12\x17\n" +
	"\aitem_id\x18\x01 \x01(\x05R\x06itemId\x12\x19\n" +
	"\bitem_num\x18\x02 \x01(\x05R\aitemNum\"#\n" +
	"\x0fgetItemList_req\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\x03R\x03uid\"3\n" +
	"\x0fgetItemList_res\x12 \n" +
	"\x04info\x18\x01 \x03(\v2\f.player_itemR\x04info\"S\n" +
	"\vplayer_item\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\x03R\x03uid\x12\x17\n" +
	"\aitem_id\x18\x02 \x01(\x05R\x06itemId\x12\x19\n" +
	"\bitem_num\x18\x03 \x01(\x05R\aitemNum\"L\n" +
	"\x0eregister_event\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\x03R\x03uid\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\"{\n" +
	"\x0eplaceOrder_req\x12\x17\n" +
	"\aitem_id\x18\x01 \x01(\tR\x06itemId\x12\x1e\n" +
	"\x04type\x18\x02 \x01(\x0e2\n" +
	".OrderTypeR\x04type\x12\x1a\n" +
	"\bquantity\x18\x03 \x01(\x05R\bquantity\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x05R\x05price\"Q\n" +
	"\x0eplaceOrder_res\x12\x19\n" +
	"\border_id\x18\x01 \x01(\x03R\aorderId\x12$\n" +
	"\x06status\x18\x02 \x01(\x0e2\f.OrderStatusR\x06status\"C\n" +
	"\x12getMarketDepth_req\x12\x17\n" +
	"\aitem_id\x18\x01 \x01(\tR\x06itemId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"V\n" +
	"\x12getMarketDepth_res\x12\x1f\n" +
	"\x04bids\x18\x01 \x03(\v2\v.OrderEntryR\x04bids\x12\x1f\n" +
	"\x04asks\x18\x02 \x03(\v2\v.OrderEntryR\x04asks\">\n" +
	"\n" +
	"OrderEntry\x12\x14\n" +
	"\x05price\x18\x01 \x01(\x05R\x05price\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\x05R\bquantity*\x1e\n" +
	"\tOrderType\x12\a\n" +
	"\x03BUY\x10\x00\x12\b\n" +
	"\x04SELL\x10\x01*I\n" +
	"\vOrderStatus\x12\v\n" +
	"\aPENDING\x10\x00\x12\x12\n" +
	"\x0ePARTIAL_FILLED\x10\x01\x12\n" +
	"\n" +
	"\x06FILLED\x10\x02\x12\r\n" +
	"\tCANCELLED\x10\x032\xe1\x01\n" +
	"\rPlayerService\x12(\n" +
	"\bregister\x12\r.register_req\x1a\r.register_res\x12:\n" +
	"\x0egetPlayerByUid\x12\x13.getPlayerByUid_req\x1a\x13.getPlayerByUid_res\x127\n" +
	"\rplayerGetItem\x12\x12.playerGetItem_req\x1a\x12.playerGetItem_res\x121\n" +
	"\vgetItemList\x12\x10.getItemList_req\x1a\x10.getItemList_res2{\n" +
	"\rMarketService\x12.\n" +
	"\n" +
	"placeOrder\x12\x0f.placeOrder_req\x1a\x0f.placeOrder_res\x12:\n" +
	"\x0egetMarketDepth\x12\x13.getMarketDepth_req\x1a\x13.getMarketDepth_resB3\n" +
	"\x16com.example.GameServerB\rMessagesProtoZ\a./;main\x88\x01\x01b\x06proto3"

var (
	file_messages_proto_rawDescOnce sync.Once
	file_messages_proto_rawDescData []byte
)

func file_messages_proto_rawDescGZIP() []byte {
	file_messages_proto_rawDescOnce.Do(func() {
		file_messages_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_messages_proto_rawDesc), len(file_messages_proto_rawDesc)))
	})
	return file_messages_proto_rawDescData
}

var file_messages_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_messages_proto_goTypes = []any{
	(OrderType)(0),            // 0: OrderType
	(OrderStatus)(0),          // 1: OrderStatus
	(*RegisterReq)(nil),       // 2: register_req
	(*RegisterRes)(nil),       // 3: register_res
	(*GetPlayerByUidReq)(nil), // 4: getPlayerByUid_req
	(*GetPlayerByUidRes)(nil), // 5: getPlayerByUid_res
	(*PlayerGetItemReq)(nil),  // 6: playerGetItem_req
	(*PlayerGetItemRes)(nil),  // 7: playerGetItem_res
	(*GetItemListReq)(nil),    // 8: getItemList_req
	(*GetItemListRes)(nil),    // 9: getItemList_res
	(*PlayerItem)(nil),        // 10: player_item
	(*RegisterEvent)(nil),     // 11: register_event
	(*PlaceOrderReq)(nil),     // 12: placeOrder_req
	(*PlaceOrderRes)(nil),     // 13: placeOrder_res
	(*GetMarketDepthReq)(nil), // 14: getMarketDepth_req
	(*GetMarketDepthRes)(nil), // 15: getMarketDepth_res
	(*OrderEntry)(nil),        // 16: OrderEntry
}
var file_messages_proto_depIdxs = []int32{
	10, // 0: getItemList_res.info:type_name -> player_item
	0,  // 1: placeOrder_req.type:type_name -> OrderType
	1,  // 2: placeOrder_res.status:type_name -> OrderStatus
	16, // 3: getMarketDepth_res.bids:type_name -> OrderEntry
	16, // 4: getMarketDepth_res.asks:type_name -> OrderEntry
	2,  // 5: PlayerService.register:input_type -> register_req
	4,  // 6: PlayerService.getPlayerByUid:input_type -> getPlayerByUid_req
	6,  // 7: PlayerService.playerGetItem:input_type -> playerGetItem_req
	8,  // 8: PlayerService.getItemList:input_type -> getItemList_req
	12, // 9: MarketService.placeOrder:input_type -> placeOrder_req
	14, // 10: MarketService.getMarketDepth:input_type -> getMarketDepth_req
	3,  // 11: PlayerService.register:output_type -> register_res
	5,  // 12: PlayerService.getPlayerByUid:output_type -> getPlayerByUid_res
	7,  // 13: PlayerService.playerGetItem:output_type -> playerGetItem_res
	9,  // 14: PlayerService.getItemList:output_type -> getItemList_res
	13, // 15: MarketService.placeOrder:output_type -> placeOrder_res
	15, // 16: MarketService.getMarketDepth:output_type -> getMarketDepth_res
	11, // [11:17] is the sub-list for method output_type
	5,  // [5:11] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_messages_proto_init() }
func file_messages_proto_init() {
	if File_messages_proto != nil {
		return
	}
	file_messages_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_messages_proto_rawDesc), len(file_messages_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_messages_proto_goTypes,
		DependencyIndexes: file_messages_proto_depIdxs,
		EnumInfos:         file_messages_proto_enumTypes,
		MessageInfos:      file_messages_proto_msgTypes,
	}.Build()
	File_messages_proto = out.File
	file_messages_proto_goTypes = nil
	file_messages_proto_depIdxs = nil
}
